// Generated by gencpp from file aprilslam/Apriltags.msg
// DO NOT EDIT!


#ifndef APRILSLAM_MESSAGE_APRILTAGS_H
#define APRILSLAM_MESSAGE_APRILTAGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <aprilslam/Apriltag.h>

namespace aprilslam
{
template <class ContainerAllocator>
struct Apriltags_
{
  typedef Apriltags_<ContainerAllocator> Type;

  Apriltags_()
    : header()
    , apriltags()  {
    }
  Apriltags_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , apriltags(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::aprilslam::Apriltag_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::aprilslam::Apriltag_<ContainerAllocator> >::other >  _apriltags_type;
  _apriltags_type apriltags;





  typedef boost::shared_ptr< ::aprilslam::Apriltags_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aprilslam::Apriltags_<ContainerAllocator> const> ConstPtr;

}; // struct Apriltags_

typedef ::aprilslam::Apriltags_<std::allocator<void> > Apriltags;

typedef boost::shared_ptr< ::aprilslam::Apriltags > ApriltagsPtr;
typedef boost::shared_ptr< ::aprilslam::Apriltags const> ApriltagsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aprilslam::Apriltags_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aprilslam::Apriltags_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aprilslam::Apriltags_<ContainerAllocator1> & lhs, const ::aprilslam::Apriltags_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.apriltags == rhs.apriltags;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aprilslam::Apriltags_<ContainerAllocator1> & lhs, const ::aprilslam::Apriltags_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aprilslam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::aprilslam::Apriltags_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aprilslam::Apriltags_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aprilslam::Apriltags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aprilslam::Apriltags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aprilslam::Apriltags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aprilslam::Apriltags_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aprilslam::Apriltags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5ae40ca0fbd4e67f1024879668dbd09";
  }

  static const char* value(const ::aprilslam::Apriltags_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5ae40ca0fbd4e67ULL;
  static const uint64_t static_value2 = 0xf1024879668dbd09ULL;
};

template<class ContainerAllocator>
struct DataType< ::aprilslam::Apriltags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aprilslam/Apriltags";
  }

  static const char* value(const ::aprilslam::Apriltags_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aprilslam::Apriltags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ApriltagsStamped\n"
"std_msgs/Header header\n"
"Apriltag[] apriltags\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: aprilslam/Apriltag\n"
"# Apriltag\n"
"int32 id\n"
"string family\n"
"float64 size\n"
"int32 hamming_distance\n"
"geometry_msgs/Point center\n"
"geometry_msgs/Point[] corners\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::aprilslam::Apriltags_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aprilslam::Apriltags_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.apriltags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Apriltags_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aprilslam::Apriltags_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aprilslam::Apriltags_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "apriltags[]" << std::endl;
    for (size_t i = 0; i < v.apriltags.size(); ++i)
    {
      s << indent << "  apriltags[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aprilslam::Apriltag_<ContainerAllocator> >::stream(s, indent + "    ", v.apriltags[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // APRILSLAM_MESSAGE_APRILTAGS_H
